dofile "Mechanics/Pizzaface"
dofile "Mechanics/Snick"
dofile "Mechanics/John Ghost"
dofile "Mechanics/Pillar John"
dofile "Mechanics/Spawn Gate"
dofile "Mechanics/Toppins"
dofile "Mechanics/Combo Bar"
dofile "Mechanics/Escape Spawner"
dofile "Mechanics/PVP"
dofile "Mechanics/Secrets"
dofile "Mechanics/Treasures"
dofile "Mechanics/Ranks"
dofile "Mechanics/Exit Signs"
dofile "Mechanics/Lap Portal"